using System;
using Epic;
using Oven.Reporting;

namespace iOven.Autogenerated
{
	public class OvenStateQuery : OvenQueryBase<IOven, IState>
	{
		public OvenStateQuery (Oven.OvenUri ovenId)
			: base(ovenId)
		{
		}

		#region implemented abstract members of Epic.QueryBase[IOven,OvenId]
		public override IState Query (IOven entity)
		{
			return entity.CurrentState;
		}
		#endregion
	}
}

